### ISSUE TITLE
NaN issue

### ISSUE THREAD

**Issue by SebastiaanKloos** [schmidfelix/timey#15]
I think the app should or show "running" instead of the €NaN or something

![CleanShot 2021-03-23 at 12 49 29](https://user-images.githubusercontent.com/6506510/112142360-c8058800-8bd6-11eb-8930-b05f3b11dfc9.png)

**Comment by schmidfelix** [comment]
Hey,

thats definite something to fix, but I'm unsure if I like "running" or a simple dash more..

<img width="335" alt="CleanShot 2021-03-23 at 15 38 21@2x" src="https://user-images.githubusercontent.com/22103266/112163987-d27f4c00-8bed-11eb-8f16-84fcfee2f54a.png">
<img width="335" alt="CleanShot 2021-03-23 at 15 38 45@2x" src="https://user-images.githubusercontent.com/22103266/112164046-df03a480-8bed-11eb-87aa-5ca0bef4f092.png">

Which version do you like more?

**Comment by schmidfelix** [comment]
Thanks for reporting, in the next release it's going to show "Running" instead of NaN.

**Comment by SebastiaanKloos** [comment]
@schmidfelix Thanks for the quick reply!

**Comment by schmidfelix** [comment]
No problem :) I've just released v1.1.0 including all the bug fixes and new features. I've also added a changelog, maybe worth a read: https://felix-schmid.de/docs/timey/v1/changelog
