### ISSUE TITLE
License asks for reactivation after closing window

### ISSUE THREAD

**Issue by mechawrench** [schmidfelix/timey#16]
Getting the following error after activating and closing the window.  When I reopen from the dock it presents this error: 
```
It seems like there is an problem with your license. Please try removing this device from your dashboard and activating it again.
If the error still occurs, please contact the support.
```
Environment: M1 Mac

I've attempted reinstalling and supplying the key again after deactivation in the portal, same error.  This is my second installation, my first install on another Mac (Non-M1) is working great.

**Comment by schmidfelix** [comment]
Hm, thats weird - seems like a M1 issue. Nevertheless, that should be fixed in version 1.1.2, which should be available now. To update your app, simply open it. After a while it will send you a notification that it will update itself at the next start.

Let me know if that solved your problem 👍
