### ISSUE TITLE
Visual issue (arrow down) time selector

### ISSUE THREAD

**Issue by SebastiaanKloos** [schmidfelix/timey#5]
![CleanShot 2021-03-23 at 12 26 59](https://user-images.githubusercontent.com/6506510/112139932-a48d0e00-8bd3-11eb-9dfb-6155b5928f28.png)

**Comment by schmidfelix** [comment]
Hey Sebastian,

thanks for reporting this - will be fixed in the next version which I plan to release later today or tomorrow!
